keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  jwk: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs

spring:
  security:
    ignored: "/actuator/**"

logging:
  level:
    org:
      springframework:
        security: INFO
      zalando:
        logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${APP_NAME}