spring:
  security:
    ignored: "/actuator/**"
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${APP_NAME}