spring:
  profiles:
    active: @active-profiles@
  security:
    ignored: "/actuator/**"

keycloak:
  jwk: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        security: INFO
      zalando:
        logbook: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"