keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}

spring:
  security:
    ignored: "/actuator/**"
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${APP_NAME}