spring:
  security:
    ignored: "/actuator/**"
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs


logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
        security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${APP_NAME}